config/routes.rb
CparSystem::Application.routes.draw do

  root to: 'static_pages#home'
  
  get "users/new"
  match '/signup',  to: 'users#new'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets
  resources :email_verifications

  resources :issue_attachments, only: [:create, :destroy]
  resources :issue_comments, only: [:create, :destroy]
  resources :action_plan_comments, only: [:create, :destroy]
  resources :issue_comments, only: [:create, :destroy]
  resources :cause_comments, only: [:create, :destroy]

  resources :issues do
    get 'details', on: :member
    resources :causes
    get 'attach_form', on: :member
  end

  resources :action_plans do
    resources :activities
  end

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :users do
      get 'activate', on: :member
    end
  end

  namespace :qmr do
    get '', to: 'dashboard#index', as: '/'
    resources :next_responsible_departments, only: [:create, :destroy]
    resources :issues do 
      get 'statuschange', on: :member
      get 'details', on: :member
      get 'edit_departments', on: :member
      get 'sign_closeout', on: :member
      get 'notify_deadline', on: :member
    end
    resources :issue_comments, only: :create
  end

  namespace :auditor do
    get '', to: 'dashboard#index', as: '/'
    resources :action_plans do
      get 'review', :on => :member
      get 'reject', on: :member
      put 'update_activities', on: :member
      put 'update_activities2', on: :member
      get 'activity_statuschange', on: :member
      get 'implemented', on: :member
      get 'not_implemented', on: :member
    end
    resources :issues do
      get 'details', on: :member
      get 'sign_closeout', on: :member
    end
    resources :closeout_forms, only: :create
    resources :issue_comments, only: :create
    resources :action_plan_comments, only: :create
  end

  namespace :officer do
    get '', to: 'dashboard#index', as: '/'
    resources :action_plans do
      resources :activities do
        get 'mark_done', on: :member
      end
      get 'implemented', :on => :member
    end
    resources :issues do
      get 'details', on: :member
      get 'sign_closeout', on: :member
      resources :causes do
        post 'create_nrd', on: :collection
      end
    end
    resources :issue_comments, only: :create
    resources :action_plan_comments, only: :create
    resources :cause_comments, only: :create
    resources :cause_attachments, only: [:create, :destroy]
  end

  namespace :dept do
    get '', to: 'dashboard#index', as: '/'
    resources :users
    resources :issues do
      get 'details', on: :member
      get 'sign_closeout', on: :member
      get 'sign_closeout2', on: :member
      put 'update_date', on: :member
      resources :causes do
        post 'create_nrd', on: :collection
      end
    end
    resources :action_plans do
      resources :activities do
        get 'mark_done', on: :member
      end
      get 'implemented', :on => :member
    end
    resources :next_responsible_departments, only: :update
    resources :issue_comments, only: :create
    resources :action_plan_comments, only: :create
    resources :cause_comments, only: :create
    resources :cause_attachments, only: [:create, :destroy]
  end

  get "sessions/new"
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@issues = Issue.all
  	@issues_closed = Issue.where("final_closeout_date between ? and ?", Date.today.at_beginning_of_month, Date.today.next_month.beginning_of_month)
  	@issues_thismonth = Issue.where("created_at between ? and ?", Date.today.at_beginning_of_month, Date.today.next_month.beginning_of_month)
    @issues_pending = Issue.where("final_closeout_date is NULL").count #.sum(:total_price)
    @issues_rejected = Issue.where("status_id = 7").count
  	# can also use this format YourModel.where(:created_at => start_date..end_date)
  	@issues_total = Issue.all.count.to_f
  	
    if @issues_total != 0
      @issues_admin = Issue.where("department_id = 1").count / @issues_total
    	@issues_maintenance = Issue.where("department_id = 2").count / @issues_total
    	@issues_development = Issue.where("department_id = 3").count / @issues_total
    	@issues_verification = Issue.where("department_id = 4").count / @issues_total
    else
      @issues_admin = 0
      @issues_maintenance = 0
      @issues_development = 0
      @issues_verification = 0
    end
    
    @average = 0
    @closed_issues = Issue.where("final_closeout_date is NOT NULL")
    @closed_issues.each do |i|
      @average += i.time_to_resolve
    end

    if @closed_issues.count == 0
      @average = 0
    else
      @average = @average / @closed_issues.count
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="page-header">
	<h1>CPAR System</h1>
	<% if signed_in? %>
		<div class ="row">
			<div class="span9" id="issues_chart" style="width: 500px; height: 400px;"></div>
			<!--This is temporary-->
			<script type="text/javascript" charset="utf-8">
				$(function () {
				  new Highcharts.Chart({
				    chart: { renderTo: 'issues_chart' },
				    title: { text: 'Issues by Day' },
				    xAxis: { type: 'datetime' },
				    yAxis: {
				      title: { text: 'Issues'}
				    },
				    tooltip: {
				      formatter: function () {
        				return Highcharts.dateFormat("%B %e %Y", this.x) + ': ' + this.y + " Issues";
      					}
    				},  
				    series: [
				    {
				    	name: "Issues Started",
				        pointInterval: <%= 1.day * 1000 %>,
      					pointStart: <%= 1.week.ago.at_midnight.to_i * 1000 %>,
      					data: <%= (1.week.ago.to_date..1.week.from_now.to_date).map { |date| Issue.total_on(date).to_f}.inspect %>
				    },
				    {
				      name: "Issues Closed",
				      pointInterval: <%= 1.day * 1000 %>,
				      pointStart: <%= 1.week.ago.at_midnight.to_i * 1000 %>,
				      data: <%= (1.week.ago.to_date..1.week.from_now.to_date).map { |date| Issue.total_closed(date).to_f}.inspect %>
				    },
				    {
				      name: "Pending Issues Estimated Closeout",
				      pointInterval: <%= 1.day * 1000 %>,
				      pointStart: <%= 1.week.ago.at_midnight.to_i * 1000 %>,
				      data: <%= (1.week.ago.to_date..1.week.from_now.to_date).map { |date| Issue.pending_on(date).to_f}.inspect %>
				    }]
				  });
				  new Highcharts.Chart({
				  	chart: { 
				  		
				  		renderTo: 'issues_chart2' },
				  	title: { text: 'Issues by Department' },
				  	tooltip: {
        	    		pointFormat: '{series.name}: <b>{point.percentage}%</b>',
            			percentageDecimals: 1
            			},
            		plotOptions: {
            		    pie: {
                    		allowPointSelect: true,
                    		cursor: 'pointer',
                    		dataLabels: {
	                        	enabled: true,
    		                    color: '#000000',
            		            connectorColor: '#000000',
                    		    formatter: function() {
                            	return '<b>'+ this.point.name +'</b>: '+ Math.round(this.percentage) +' %';
                        		}
                    		}
                		}
            		},
            		series: [{
                		type: 'pie',
                		name: 'Issues by Department',
                		data: [
                			
                    		['Administration',   <%= @issues_admin  %>],
		                    ['Maintenance',       <%= @issues_maintenance %>],
                    		['Development',    <%= @issues_development %>],
                    		['Verification',     <%= @issues_verification %>],
                		]
                	}]
				  });
				new Highcharts.Chart({ 
					 chart: {
		                type: 'bar',
		                renderTo: 'issues_chart3'
		            },
		            title: {
		                text: 'Issues Statuses'
		            },
		            subtitle: {
		                text: 'by Department'
		            },
		            xAxis: {
		                categories: ['New', 'Verified', 'Investigating', 'Correcting', 'Implemented', 'Closed', 'Rejected'],
		                title: {
		                    text: null
		                }
		            },
		            yAxis: {
		                min: 0,
		                title: {
		                    text: 'Issues',
		                    align: 'high'
		                },
		                labels: {
		                    overflow: 'justify'
		                }
		            },
		            tooltip: {
		                valueSuffix: ' Issues'
		            },
		            plotOptions: {
		                bar: {
		                    dataLabels: {
		                        enabled: true
		                    }
		                }
		            },
		            legend: {
		                layout: 'vertical',
		                align: 'right',
		                verticalAlign: 'top',
		                x: -20,
		                y: 20,
		                floating: true,
		                borderWidth: 1,
		                backgroundColor: '#FFFFFF',
		                shadow: true
		            },
		            credits: {
		                enabled: false
		            },
		            series: [{
		                name: 'Administration',
		                data: [<%= Issue.where(status_id: 1, department_id: 1).count %>, <%= Issue.where(status_id: 2, department_id: 1).count %>, <%= Issue.where(status_id: 3, department_id: 1).count %>,<%= Issue.where(status_id: 4, department_id: 1).count%>,<%= Issue.where(status_id: 5, department_id: 1).count%>,<%= Issue.where(status_id: 6, department_id: 1).count%>, ,<%= Issue.where(status_id: 7, department_id: 1).count %>]
		            }, {
		                name: 'Maintenance',
		                data: [<%= Issue.where(status_id: 1, department_id: 2).count %>, <%= Issue.where(status_id: 2, department_id: 2).count %>, <%= Issue.where(status_id: 3, department_id: 2).count %>, <%= Issue.where(status_id: 4, department_id: 2).count %>, <%= Issue.where(status_id: 5, department_id: 2).count %>, <%= Issue.where(status_id: 6, department_id: 2).count %>, <%= Issue.where(status_id: 7, department_id: 2).count %>]
		            }, {
		                name: 'Development',
		                data: [<%= Issue.where(status_id: 1, department_id: 3).count %>, <%= Issue.where(status_id: 2, department_id: 3).count %>, <%= Issue.where(status_id: 3, department_id: 3).count %>, <%= Issue.where(status_id: 4, department_id: 3).count %>, <%= Issue.where(status_id: 5, department_id: 3).count %>, <%= Issue.where(status_id: 6, department_id: 3).count %>, <%= Issue.where(status_id: 7, department_id: 3).count %>]
		            }, {
		                name: 'Verification',
		                data: [<%= Issue.where(status_id: 1, department_id: 4).count %>, <%= Issue.where(status_id: 2, department_id: 4).count %>, <%= Issue.where(status_id: 3, department_id: 4).count %>, <%= Issue.where(status_id: 4, department_id: 4).count %>, <%= Issue.where(status_id: 5, department_id: 4).count %>, <%= Issue.where(status_id: 6, department_id: 4).count %>, <%= Issue.where(status_id: 7, department_id: 4).count %>]
		            }]
				});
			});
			</script>
			<div class="span3" id="issues_chart2" style="width: 400px; height: 400px;"></div>
			<div class="span6" id="issues_chart3" style="width: 500px; height: 600px;"></div>
			<div class="span3">
				<p></p>
				<br>
				<hr>
				<table class="table table-striped table-bordered">
			    <tr>
			      <th>Issues Summary</th>
			      <th></th>
			  	</tr>
			  	<tr>
			  		<td>All Issues</td>
					<td><%= @issues.count.to_s %></td>
				</tr>
				<tr>
			  		<td>Issues Submitted this month</td>
					<td><%= @issues_thismonth.count.to_s %></td>
				</tr>
				<tr>
			  		<td>Issues Closed this month</td>
					<td><%= @issues_closed.count.to_s %></td>
				</tr>
				<tr>
			  		<td>Pending Issues</td>
					<td><%= @issues_pending.to_s %></td>
				</tr>
				<tr>
			  		<td>Issue Rejection Rate</td>
					<td><%= ((@issues_rejected / @issues_total) * 100).to_s + " %" if @issues_total != 0 %></td>
				</tr>
				<tr>
			  		<td>Average Days to Resolve Issues</td>
					<td><%= @average %></td>
				</tr>
			</table>
			</div>
		</div>
	</div>
	<% else %>
		<h2>
		  Please login to use features.
		  <p><%= link_to "Sign In", signin_path, class: "btn btn-large btn-primary" %>
		  	 <%= link_to "Sign Up", signup_path, class: "btn btn-large btn-primary" %>
			</p>
			</h2>
	<% end %>
</div>