config/routes.rb
CparSystem::Application.routes.draw do

  root to: 'static_pages#home'
  
  get "users/new"
  match '/signup',  to: 'users#new'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets
  resources :email_verifications

  resources :issue_attachments, only: [:create, :destroy]
  resources :issue_comments, only: [:create, :destroy]
  resources :action_plan_comments, only: [:create, :destroy]
  resources :issue_comments, only: [:create, :destroy]
  resources :cause_comments, only: [:create, :destroy]

  resources :issues do
    get 'details', on: :member
    resources :causes
    get 'attach_form', on: :member
  end

  resources :action_plans do
    resources :activities
  end

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :users do
      get 'activate', on: :member
    end
  end

  namespace :qmr do
    get '', to: 'dashboard#index', as: '/'
    resources :next_responsible_departments, only: [:create, :destroy]
    resources :issues do 
      get 'statuschange', on: :member
      get 'details', on: :member
      get 'edit_departments', on: :member
      get 'sign_closeout', on: :member
      get 'notify_deadline', on: :member
    end
    resources :issue_comments, only: :create
  end

  namespace :auditor do
    get '', to: 'dashboard#index', as: '/'
    resources :action_plans do
      get 'review', :on => :member
      get 'reject', on: :member
      put 'update_activities', on: :member
      put 'update_activities2', on: :member
      get 'activity_statuschange', on: :member
      get 'implemented', on: :member
      get 'not_implemented', on: :member
    end
    resources :issues do
      get 'details', on: :member
      get 'sign_closeout', on: :member
    end
    resources :closeout_forms, only: :create
    resources :issue_comments, only: :create
    resources :action_plan_comments, only: :create
  end

  namespace :officer do
    get '', to: 'dashboard#index', as: '/'
    resources :action_plans do
      resources :activities do
        get 'mark_done', on: :member
      end
      get 'implemented', :on => :member
    end
    resources :issues do
      get 'details', on: :member
      get 'sign_closeout', on: :member
      resources :causes do
        post 'create_nrd', on: :collection
      end
    end
    resources :issue_comments, only: :create
    resources :action_plan_comments, only: :create
    resources :cause_comments, only: :create
    resources :cause_attachments, only: [:create, :destroy]
  end

  namespace :dept do
    get '', to: 'dashboard#index', as: '/'
    resources :users
    resources :issues do
      get 'details', on: :member
      get 'sign_closeout', on: :member
      get 'sign_closeout2', on: :member
      put 'update_date', on: :member
      resources :causes do
        post 'create_nrd', on: :collection
      end
    end
    resources :action_plans do
      resources :activities do
        get 'mark_done', on: :member
      end
      get 'implemented', :on => :member
    end
    resources :next_responsible_departments, only: :update
    resources :issue_comments, only: :create
    resources :action_plan_comments, only: :create
    resources :cause_comments, only: :create
    resources :cause_attachments, only: [:create, :destroy]
  end

  get "sessions/new"
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/issue_type.rb
class IssueType < ActiveRecord::Base
  has_many :issues

  attr_accessible :description, :name
end

app/controllers/auditor/issues_controller.rb
class Auditor::IssuesController < ApplicationController
  before_filter :signed_in_user
  before_filter :auditor_user

  def show
  	@issue = Issue.find params[:id]
    # moved Causes and ActionPlans to details view
    @action_plans_implemented = ActionPlan.where(issue_id: @issue.id, ap_status_id: 5)
    @closeoutforms= CloseoutForm.where(issue_id: @issue.id)
    @closeoutform = CloseoutForm.new
    #@cof = CloseoutForm.find_by_issue_id(@issue.id) #should be in details
    @action_plans = ActionPlan.where("issue_id = " + @issue.id.to_s).paginate(page: params[:page], per_page: 5)
    @issue_comment = IssueComment.new
    @issuecomments = @issue.issue_comments.where(log_comment: 'f').paginate(page: params[:page],  per_page: 3)
    @issueupdates = @issue.issue_comments.where(log_comment: 't').paginate(page: params[:page],  per_page: 5)
  end

  def index
  	if params[:sort] != nil
      @issues = Issue.where("status_id = " + params[:sort]).paginate(page: params[:page], per_page: 10)
    else
     @issues = Issue.paginate(page: params[:page], per_page: 10)
    end
  end

  def sign_closeout
    @issue = Issue.find params[:id]
    @cof = CloseoutForm.find_by_id(params[:cof])
    if @cof.auditor_id == nil 
      @cof.auditor_id = current_user.id
      if @cof.save
        @ic= @issue.issue_comments.build({content: "Auditor signed Closeout Form.",
            user_id: current_user.id, issue_id: @issue.id })
        @ic.toggle!(:log_comment)
        @ic.save
        flash[:success] = "Successfully signed Closeout form of Issue!"
        redirect_to details_auditor_issue_path(@issue)
      end
    end
  end

  def details
    @issue = Issue.find params[:id]
    @causes= @issue.causes.paginate(page: params[:page],  per_page: 5)
    @action_plans = ActionPlan.where("issue_id = " + @issue.id.to_s).paginate(page: params[:page], per_page: 5)
    @cof = CloseoutForm.find_by_issue_id(@issue.id)
  end

  private

  def auditor_user
      redirect_to(root_path) unless current_user.type_id==5
  end
  # Check for uniqueness later of Dept_id inside one COF before generating
end

app/controllers/dept/issues_controller.rb
class Dept::IssuesController < ApplicationController
  before_filter :signed_in_user
  before_filter :dept_user
  before_filter :correct_department, only: :show

  def index
    if params[:sort] != nil
      @issues_all = Issue.where("status_id = " + params[:sort])
      @issues = Array.new
      @issues_all.each do |issue|
        if issue.found_department(current_user.department_id)
          @issues << issue
        end
      end
      @issues = @issues.paginate(page: params[:page], per_page: 10)
    else
      @issues_all = Issue.all
      @issues = Array.new
      @issues_all.each do |issue|
        if issue.found_department(current_user.department_id)
          @issues << issue
        end
      end
      @issues = @issues.paginate(page: params[:page], per_page: 10)
    end  
  end

  def sign_closeout
    @issue = Issue.find params[:id]
    @cofd = CloseoutFormDept.find_by_id(params[:cofd])
    if @cofd.dept_head_id == nil 
      @cofd.dept_head_id = current_user.id
      if @cofd.save
        @ic= @issue.issue_comments.build({content: "Dept Head signed Closeout Form.",
            user_id: current_user.id, issue_id: @issue.id })
        @ic.toggle!(:log_comment)
        @ic.save
        flash[:success] = "Successfully signed Closeout form of Issue!"
        redirect_to details_dept_issue_path(@issue)
      end
    end
  end

  def sign_closeout2
    @issue = Issue.find params[:id]
    @cofd = CloseoutFormDept.find_by_id(params[:cofd])
    if @cofd.officer_id == nil 
      @cofd.officer_id = current_user.id
      if @cofd.save
        @ic= @issue.issue_comments.build({content: "Officer signed Closeout Form.",
            user_id: current_user.id, issue_id: @issue.id })
        @ic.toggle!(:log_comment)
        @ic.save
        flash[:success] = "Successfully signed Closeout form of Issue!"
        redirect_to details_dept_issue_path(@issue)
      end
    end
  end

  def details
    @issue = Issue.find params[:id]
    @causes= @issue.causes.paginate(page: params[:page],  per_page: 5)
    @action_plans = ActionPlan.where("issue_id = " + @issue.id.to_s).paginate(page: params[:page], per_page: 5)
    @cof = CloseoutForm.find_by_issue_id(@issue.id)
  end

  def update
    # Dept/Issues update Would only ever be called by Assign (assign Officer) button
    @issue = Issue.find params[:id]
    @issue.status_id = 3 # Change from Verified to Investigating
    # Sure Verified first because of Assign form condition
    if @issue.update_attributes params[:issue]
      @ic= @issue.issue_comments.build({content: "Dept Head assigned an Officer to Issue.",
            user_id: current_user.id, issue_id: @issue.id })
      @ic.toggle!(:log_comment)
      @ic.save
      flash[:success] = 'Successfully Assigned Officer to Issue. Issue is now Investigating.'
      redirect_to dept_issues_path
      title = "Assigned Officer to an Issue"
      content = "You have been assigned by your Department Head as a Responsible Officer for an Issue. Please check back into the site for the Issue details."
      @officer = User.find(params[:issue][:responsible_officer_id])
      @officer.send_notification_email(title, content)
    else
      flash[:error] = 'There was an error in assigning.'
      redirect_to :back
    end
  end

  def update_date
    @issue = Issue.find params[:id]
    #@issue.estimated_closeout_date = params[:issue][:estimated_closeout_date]
    if @issue.update_attributes params[:issue]
      @ic= @issue.issue_comments.build({content: "Dept Head updated Closeout Date for Issue.",
            user_id: current_user.id, issue_id: @issue.id })
      @ic.toggle!(:log_comment)
      @ic.save
      flash[:success] = "Successfully updated Issue Closeout date!"
      redirect_to [:dept, @issue]
    else
      flash[:error] = "There was an error saving your chosen date."
      redirect_to :back
    end
  end

  def show
  	@issue = Issue.find params[:id]
    @users = User.where("department_id = " + current_user.department_id.to_s + " AND type_id = 3")
    # moved Causes and ActionPlans to details view
    @users_dept = User.where("department_id = " + current_user.department_id.to_s + " AND type_id = 2")
    @causes= @issue.causes.paginate(page: params[:page],  per_page: 5)
    @action_plans = ActionPlan.where("issue_id = " + @issue.id.to_s).paginate(page: params[:page], per_page: 5)
    # Department Head assign
    @nrd= nrd_for_this(@issue)
    @issue_comment = IssueComment.new
    @issuecomments = @issue.issue_comments.where(log_comment: 'f').paginate(page: params[:page],  per_page: 3)
    @issueupdates = @issue.issue_comments.where(log_comment: 't').paginate(page: params[:page],  per_page: 5)
  end

  private
  def dept_user
      redirect_to(root_path) unless current_user.type_id==2
  end

  def nrd_for_this(issue)
    @nrds = NextResponsibleDepartment.where("issue_id = ?", issue.id)
    my_nrd = NextResponsibleDepartment.new
    @nrds.each do |n|
      if n.department_id == current_user.department_id
        my_nrd=n
      end
    end
    my_nrd
  end

  def correct_department
    @issue = Issue.find params[:id]
    @nrds = NextResponsibleDepartment.where("issue_id = ?", @issue.id)
    found_nrds = false
    @nrds.each do |n|
      if n.department_id == current_user.department_id
        found_nrds = true
      end
    end
    if found_nrds
      #flash[:success] = "Viewing Issue Secondarily assigned to your Department" 
    elsif current_user.department_id != @issue.department_id
      flash[:error] = "You cannot view an Issue not assigned to your Department."
      redirect_to dept_issues_path
    end
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_filter :signed_in_user, only: [:index, :show, :new, :edit]
  before_filter :correct_submitter, only: [:edit, :attach_form]
  before_filter :correct_department, only: [:show]

  def index
    if params[:sort] != nil && params[:sort] == 'yours'  #get issues reported to you or your department
      @issues = Issue.where("user_id = " + current_user.id.to_s).paginate(page: params[:page], per_page: 10)
    else
      if current_user.admin?  #super admin
        @issues = Issue.paginate(page: params[:page], per_page: 10 )
      else
        @issues_all = Issue.all
        @issues = Array.new
        @issues_all.each do |issue|
          if issue.found_department(current_user.department_id)
            @issues << issue
          end
        end
        @issues = @issues.paginate(page: params[:page], per_page: 10)
      end
    end
  end

  def new
    @issue = Issue.new
  end

  def create
    @issue = Issue.new params[:issue]
    if @issue.save
      @ic= @issue.issue_comments.build({content: "User submitted Issue.",
            user_id: current_user.id, issue_id: @issue.id })
      @ic.toggle!(:log_comment)
      @ic.save
      flash[:success] = 'The issue has been created!'
      redirect_to issues_path
    else
      flash[:error]='There was an error in creating your issue.'
      redirect_to :back
    end
  end

  def show
    @issue = Issue.find params[:id]
    @causes= @issue.causes.paginate(page: params[:page],  per_page: 5)
    @action_plans = ActionPlan.where("issue_id = " + @issue.id.to_s).paginate(page: params[:page], per_page: 5)
    @issue_comment = IssueComment.new
    @issuecomments = @issue.issue_comments.where(log_comment: 'f').paginate(page: params[:page],  per_page: 3)
    @issueupdates = @issue.issue_comments.where(log_comment: 't').paginate(page: params[:page],  per_page: 5)
  end

  def attach_form
    @issue = Issue.find params[:id]
    @issue_attachment = IssueAttachment.new
  end

  def details
    @issue = Issue.find params[:id]
    @causes= @issue.causes.paginate(page: params[:page],  per_page: 5)
    @action_plans = ActionPlan.where("issue_id = " + @issue.id.to_s).paginate(page: params[:page], per_page: 5)
    @cof = CloseoutForm.find_by_issue_id(@issue.id)
  end

  def edit
    @issue = Issue.find params[:id]
    @issue_attachment = IssueAttachment.new
  end

  def update
    issue = Issue.find params[:id]
    if issue.update_attributes params[:issue]
      @ic= issue.issue_comments.build({content: "User updated their submitted Issue's details.",
            user_id: current_user.id, issue_id: issue.id })
      @ic.toggle!(:log_comment)
      @ic.save
      flash[:success] = "The issue has been updated successfully!"
      redirect_to issue_path  
    else
      flash[:error] = "There was an error in updating your issue."
      redirect_to :back
    end
  end

private
  def correct_department
    @issue = Issue.find params[:id]
    if !current_user.admin? 
      #remove this condition if admin mustn't be allowed to view all Issues in public
      if current_user.id == @issue.user_id
        #flash[:success] = "Viewing your submitted Issue."
      elsif @issue.found_department(current_user.department_id)  
        # Still viewable to secondarily assigned
      else
        flash[:error] = "You cannot view that Issue."
        redirect_to issues_path
      end
    end 
  end

  def correct_submitter
    @issue = Issue.find params[:id]
    if current_user.id != @issue.user_id 
      flash[:error] = "You cannot Edit that Issue."
      redirect_to issue_path
    end
  end

end

app/helpers/auditor/issues_helper.rb
module Auditor::IssuesHelper
end

app/helpers/dept/issues_helper.rb
module Dept::IssuesHelper
	def found_dept(issue)
		found_dep=false
		if issue.department_id == current_user.department_id
			found_dep = true
		else
			@nrds = NextResponsibleDepartment.where("issue_id = ?", issue.id)
    		@nrds.each do |n|
      			if n.department_id == current_user.department_id
        			found_dep = true
      			end
    		end
		end
		found_dep
	end

	def found_officer_id(issue)
    found = false
    if issue.responsible_officer_id && issue.responsible_officer_id == current_user.id
      found = true
    else
      issue.next_responsible_departments.each do |nrd|
        if nrd.responsible_officer_id && nrd.responsible_officer_id == current_user.id
          found = true
        end
      end
    end
    found
  end
end

app/helpers/issues_helper.rb
module IssuesHelper
	def preview_or_default_image(media)
      case media.myfile.file.extension #image is name of uploader class
      when 'jpg', 'jpeg', 'png', 'gif' # , 'png', ...
        media.myfile_url
      #when 'doc', 'docx'
      #  '#{RAILS_ROOT}/public/default_image.png'
      #when 'xls', 'xlsx'
      #  '#{RAILS_ROOT}/public/default_image.png'
      #when 'pdf'
      #  '#{RAILS_ROOT}/public/default_image.png'
      else
        '#{RAILS_ROOT}/public/uploads/issue_attachment/myfile/2/test.gif'
      end
  end
end

app/helpers/officer/issues_helper.rb
module Officer::IssuesHelper
	def found_officer_id(issue)
    found = false
    if issue.responsible_officer_id && issue.responsible_officer_id == current_user.id
      found = true
    else
      issue.next_responsible_departments.each do |nrd|
        if nrd.responsible_officer_id && nrd.responsible_officer_id == current_user.id
          found = true
        end
      end
    end
    found
  end
end

app/helpers/qmr/issues_helper.rb
module Qmr::IssuesHelper
  def status_change(stat_id)
  	case stat_id
  	when 1
  		2
  	when 2
  		3
  	when 3
  		4	
  	when 4
  		5
  	else
  		5
  	end
  end

  def status_display(stat_id)
  	IssueStatus.find(stat_id+1).name
  end

  def closeoutform_finished(cof)
    finished = true
    # No need to check for Auditor id, because it's added as soon as COF is created,
    # along with CloseoutFormDepts and their corresponding Dept_ids
    cof.closeout_form_depts.each do |cofd|
      if cofd.dept_head_id == nil || cofd.officer_id == nil
        finished = false
      end
    end
    finished
  end
end

app/views/issues/_actionplans_show.html.erb
<!--Functions as Action Plan index show for Current Issue -->
<h3>Showing Action Plans</h3>
<p>Action Plans found for this Issue: <%= @action_plans.count %></p>

<table class="table table-striped table-bordered">
    <tr>
      <th>Description</th>
      <th>Submitted by</th>
      <th>Status</th>
      <th>Final Review Date</th>
      <th>Final Implementation Date</th>
      <th></th>

    </tr>

    <% @action_plans.each do |ap| %>
      <tr>
        <td><%= ap.description %></td>
        <td><% if ap.responsible_officer_id == nil %> 
              User Name
            <% else %>
              <%= User.find(ap.responsible_officer_id).name %>
            <% end %>
        </td>
        <td><%= ActionPlanStatus.find(ap.ap_status_id).name %></td>
        <td><%= ap.final_review_date %></td>
        <td><%= ap.final_implementation_review_date %></td>
        <td> 
          <%= link_to "View", ap, class: "btn btn-primary" %>
        </td>
      </tr>
    <% end %>
</table>
<%= will_paginate @action_plans %>

app/views/issues/_attachedfiles_show.html.erb
  <div class="span5">
    <h4>Files</h4>
    <hr>
    <% if @issue.issue_attachments.any? %>
      <%= @issue.issue_attachments.count %> files attached to this Issue:
      <% @issue.issue_attachments.each do |issue_attachment| %>
        <p>
          <!--<% if issue_attachment.myfile.file.extension == 'pdf' || issue_attachment.myfile.file.extension == 'doc' || issue_attachment.myfile.file.extension == 'docx'%>
            <%= image_tag preview_or_default_image(issue_attachment) if issue_attachment.myfile? %>
            <iframe src=<%= ["http://docs.google.com/gview?url=", Rails.root.join(issue_attachment.myfile_url), "&embedded=true"].join %> style="width:600px; height:500px;" frameborder="0"></iframe>
          <% else %>
            <%= image_tag preview_or_default_image(issue_attachment) if issue_attachment.myfile? %>
          <% end %>-->
          <% if issue_attachment.myfile.file.extension == 'pdf' || issue_attachment.myfile.file.extension == 'doc' || issue_attachment.myfile.file.extension == 'docx' %>
            <i class="icon-file"></i>
          <% elsif issue_attachment.myfile.file.extension == 'jpg' || issue_attachment.myfile.file.extension == 'jpeg' || issue_attachment.myfile.file.extension == 'png' || issue_attachment.myfile.file.extension == 'bmp'|| issue_attachment.myfile.file.extension == 'gif' %>
            <i class="icon-picture"></i>
          <% else %>
            <i class="icon-search"></i>
          <% end %>
          <b><i><%= link_to File.basename(issue_attachment.myfile.url), issue_attachment.myfile.url %></i></b> | 
          <%= issue_attachment.description %> |
          <%= link_to "View file", issue_attachment.myfile.url, target: '_blank' %>
          <% if current_user.id == issue_attachment.user_id || current_user.admin %>
            | <%= link_to "delete", issue_attachment_path(issue_attachment, issue_id: @issue.id), confirm: "Are you sure you want to delete this File?", method: :delete  %>
          <% end %>
        </p>
        <br>
      <% end %>
    <% end %>
  </div>

app/views/issues/details.html.erb
<% provide(:title, 'Issue Details') %>
<h2>Issue Details</h2>
<div class="row">
  <div class="span6">
    <p id="notice"> <%= notice %> </p>
 
    <h3>
      <!--<b>Title:</b> Use this instead for header-->
      <%= @issue.title %>
    </h3>
    
    <p>
      <b>Status:</b>
      <%= @issue.issue_status.name %>
    </p>

    <p>
      <b>Estimated Closeout Date:</b>
      <%= @issue.estimated_closeout_date %>
    </p>

    <hr>

    <p>
      <b>Description:</b>
      <%= @issue.description %>
    </p>
 
    <p>
      <b>Originator:</b>
      <%= @issue.user.name %>
    </p>

    <p>
      <b>Originator Email:</b>
      <%= @issue.user.email %>
    </p>

    <p>
      <b>Departments:</b>
      <%= @issue.department.name %>
      <% if @issue.next_responsible_departments.any? %>
        <% @issue.next_responsible_departments.each do |nrd| %>
          <%= ", "+ Department.where(id: nrd.department_id).first.name %>
          <!--+ " (" + nrd.responsibility_level.to_s + ")"-->
        <% end %>
      <% end %>
    </p>

    <p>
      <b>Type:</b>
      <%= @issue.issue_type.name %>
    </p>
 
    <p>
      <b>Impact:</b>
      <% if @issue.impact_id == 1 %>
        <span class="label label-important"><%= @issue.issue_impact.name %></spn>
      <% elsif @issue.impact_id == 2 %>
        <span class="label label-warning"><%= @issue.issue_impact.name %></spn>
      <% else %>
        <span class="label label-info"><%= @issue.issue_impact.name %></spn>
      <% end %>
    </p>

    <p>
      <b>ISO Reference ID:</b>
      <%= @issue.iso_nc.title %>
    </p>

    <p>
      <b>Assigned Officer: </b> 
        <% if @issue.responsible_officer_id != nil %>
          <%= User.find(@issue.responsible_officer_id).name %>
        <% else %>
          None
        <% end %>
    </p>
    <% if @issue.user_id == current_user.id %>
      <%= link_to 'Edit', edit_issue_path(@issue), class: "btn btn-primary" %>
    <% end %>
    <%= link_to 'Back to Issue', issue_path(@issue), class: "btn btn-primary" %>
  </div>

  <div class="span9">
    <hr>
    <%= render 'departments_show' %>
    <%= render 'causes_show' %>
    <%= render 'actionplans_show' %>
    <%= render 'closeoutform_show' %>
  </div>

app/views/issues/index.html.erb
<% provide(:title, 'Issues Index') %>

<ul class="nav nav-pills">
  <li class="<%= 'active' if params[:sort] == nil %>"><%= link_to "Department Issues", issues_path %></li>
  <li class="<%= 'active' if params[:sort] == 'yours' %>"><%= link_to "My Issues", issues_path(sort: 'yours') %></li>
  <li></li>
</ul>

  <% if params[:sort] == nil %>
    <h1>View All Issues</h1>
    <h2>Department: <%= Department.where(id: current_user.department_id).first.name %></h2>
  <% else %>
    <h1>Viewing your Submitted Issues</h1>
  <% end %>


  <table class="table table-striped table-bordered">
    <tr>
      <th>Title</th>
      <th>Originator</th>
      <th>Impact</th>
      <th>Status</th>
      <th>Main Department</th>
      <th>Assigned To</th>
      <!--Add condition to show only Details link if Admin/Roled-->
      <th></th>
    </tr>

    <% @issues.each do |issue| %>
    	<tr>
        <td> <%= link_to issue.title, issue %> </td>
        <td> <%= User.find(issue.user_id).name %> </td>
        <td> <% if issue.impact_id == 1 %>
              <span class="label label-important"><%= issue.issue_impact.name %></spn>
              <% elsif issue.impact_id == 2 %>
                <span class="label label-warning"><%= issue.issue_impact.name %></spn>
              <% else %>
                <span class="label label-info"><%= issue.issue_impact.name %></spn>
            <% end %>
        </td>
        <td> <%= issue.issue_status.name %> </td>       
        <td><%= issue.department.name %></td>
        <td><% if issue.responsible_officer_id == nil %>
                None
             <% else %>
                <%= User.find(issue.responsible_officer_id).name %>
             <% end %>
        </td>
        <!--Add condition to show only Details link if Admin/Roled-->
        <td><%= link_to 'Details', details_issue_path(issue), class: "btn btn-primary" %></td>
    	</tr>

    <% end %>

  </table>
  <%= will_paginate @issues %>
<%= link_to 'Report New Issue', new_issue_path, class: "btn btn-large btn-primary" %>

app/views/issues/new.html.erb
<% provide(:title, 'New Issue') %>
<h1>New Issue</h1>

<div class="row">
  <div class="span6 offset3">
      <%= render 'issueform' %>
      <%= link_to 'Back', issues_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/issues/show.html.erb
<% provide(:title, 'Show Issue') %>
<div class="row">
  <div class="span6">
    <p id="notice"> <%= notice %> </p>
 
    <h3>
      <!--<b>Title:</b> Use this instead for header-->
      <%= @issue.title %>
    </h3>
    
    <p>
      <b>Status:</b>
      <%= @issue.issue_status.name %>
    </p>

    <p>
      <b>Estimated Closeout Date:</b>
      <%= @issue.estimated_closeout_date %>
    </p>

    <hr>

    <h4>Issue Details</h4>

    <p>
      <b>Description:</b>
      <%= @issue.description %>
    </p>
 
    <p>
      <b>Originator:</b>
      <%= @issue.user.name %>
    </p>

    <p>
      <b>Originator Email:</b>
      <%= @issue.user.email %>
    </p>

    <p>
      <b>Departments:</b>
      <%= @issue.department.name %>
      <% if @issue.next_responsible_departments.any? %>
        <% @issue.next_responsible_departments.each do |nrd| %>
          <%= ", "+ Department.where(id: nrd.department_id).first.name %>
          <!--+ " (" + nrd.responsibility_level.to_s + ")"-->
        <% end %>
      <% end %>
    </p>

    <p>
      <b>Type:</b>
      <%= @issue.issue_type.name %>
    </p>
 
    <p>
      <b>Impact:</b>
      <% if @issue.impact_id == 1 %>
        <span class="label label-important"><%= @issue.issue_impact.name %></spn>
      <% elsif @issue.impact_id == 2 %>
        <span class="label label-warning"><%= @issue.issue_impact.name %></spn>
      <% else %>
        <span class="label label-info"><%= @issue.issue_impact.name %></spn>
      <% end %>
    </p>

    <p>
      <b>ISO Reference ID:</b>
      <%= @issue.iso_nc.title %>
    </p>

    <p>
      <b>Assigned Officer: </b> 
        <% if @issue.responsible_officer_id != nil %>
          <%= User.find(@issue.responsible_officer_id).name %>
        <% else %>
          None
        <% end %>
    </p>
    <%= link_to 'Show Details', details_issue_path, class: "btn btn-primary" %>
    <% if @issue.user_id == current_user.id %>
      <%= link_to 'Edit', edit_issue_path(@issue), class: "btn btn-primary" %>
      <%= link_to 'Attach File', attach_form_issue_path(@issue, id: @issue.id), class: "btn btn-primary" %> 
    <% end %>
    <%= link_to 'Back', issues_path, class: "btn btn-primary" %>
    <hr>
    <%= render 'attachedfiles_show' %>
  </div>
  <%= render 'comments_show' %>
  
</div>