config/routes.rb
CparSystem::Application.routes.draw do

  root to: 'static_pages#home'
  
  get "users/new"
  match '/signup',  to: 'users#new'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets
  resources :email_verifications

  resources :issue_attachments, only: [:create, :destroy]
  resources :issue_comments, only: [:create, :destroy]
  resources :action_plan_comments, only: [:create, :destroy]
  resources :issue_comments, only: [:create, :destroy]
  resources :cause_comments, only: [:create, :destroy]

  resources :issues do
    get 'details', on: :member
    resources :causes
    get 'attach_form', on: :member
  end

  resources :action_plans do
    resources :activities
  end

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :users do
      get 'activate', on: :member
    end
  end

  namespace :qmr do
    get '', to: 'dashboard#index', as: '/'
    resources :next_responsible_departments, only: [:create, :destroy]
    resources :issues do 
      get 'statuschange', on: :member
      get 'details', on: :member
      get 'edit_departments', on: :member
      get 'sign_closeout', on: :member
      get 'notify_deadline', on: :member
    end
    resources :issue_comments, only: :create
  end

  namespace :auditor do
    get '', to: 'dashboard#index', as: '/'
    resources :action_plans do
      get 'review', :on => :member
      get 'reject', on: :member
      put 'update_activities', on: :member
      put 'update_activities2', on: :member
      get 'activity_statuschange', on: :member
      get 'implemented', on: :member
      get 'not_implemented', on: :member
    end
    resources :issues do
      get 'details', on: :member
      get 'sign_closeout', on: :member
    end
    resources :closeout_forms, only: :create
    resources :issue_comments, only: :create
    resources :action_plan_comments, only: :create
  end

  namespace :officer do
    get '', to: 'dashboard#index', as: '/'
    resources :action_plans do
      resources :activities do
        get 'mark_done', on: :member
      end
      get 'implemented', :on => :member
    end
    resources :issues do
      get 'details', on: :member
      get 'sign_closeout', on: :member
      resources :causes do
        post 'create_nrd', on: :collection
      end
    end
    resources :issue_comments, only: :create
    resources :action_plan_comments, only: :create
    resources :cause_comments, only: :create
    resources :cause_attachments, only: [:create, :destroy]
  end

  namespace :dept do
    get '', to: 'dashboard#index', as: '/'
    resources :users
    resources :issues do
      get 'details', on: :member
      get 'sign_closeout', on: :member
      get 'sign_closeout2', on: :member
      put 'update_date', on: :member
      resources :causes do
        post 'create_nrd', on: :collection
      end
    end
    resources :action_plans do
      resources :activities do
        get 'mark_done', on: :member
      end
      get 'implemented', :on => :member
    end
    resources :next_responsible_departments, only: :update
    resources :issue_comments, only: :create
    resources :action_plan_comments, only: :create
    resources :cause_comments, only: :create
    resources :cause_attachments, only: [:create, :destroy]
  end

  get "sessions/new"
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/controllers/auditor/issues_controller.rb
class Auditor::IssuesController < ApplicationController
  before_filter :signed_in_user
  before_filter :auditor_user

  def show
  	@issue = Issue.find params[:id]
    # moved Causes and ActionPlans to details view
    @action_plans_implemented = ActionPlan.where(issue_id: @issue.id, ap_status_id: 5)
    @closeoutforms= CloseoutForm.where(issue_id: @issue.id)
    @closeoutform = CloseoutForm.new
    #@cof = CloseoutForm.find_by_issue_id(@issue.id) #should be in details
    @action_plans = ActionPlan.where("issue_id = " + @issue.id.to_s).paginate(page: params[:page], per_page: 5)
    @issue_comment = IssueComment.new
    @issuecomments = @issue.issue_comments.where(log_comment: 'f').paginate(page: params[:page],  per_page: 3)
    @issueupdates = @issue.issue_comments.where(log_comment: 't').paginate(page: params[:page],  per_page: 5)
  end

  def index
  	if params[:sort] != nil
      @issues = Issue.where("status_id = " + params[:sort]).paginate(page: params[:page], per_page: 10)
    else
     @issues = Issue.paginate(page: params[:page], per_page: 10)
    end
  end

  def sign_closeout
    @issue = Issue.find params[:id]
    @cof = CloseoutForm.find_by_id(params[:cof])
    if @cof.auditor_id == nil 
      @cof.auditor_id = current_user.id
      if @cof.save
        @ic= @issue.issue_comments.build({content: "Auditor signed Closeout Form.",
            user_id: current_user.id, issue_id: @issue.id })
        @ic.toggle!(:log_comment)
        @ic.save
        flash[:success] = "Successfully signed Closeout form of Issue!"
        redirect_to details_auditor_issue_path(@issue)
      end
    end
  end

  def details
    @issue = Issue.find params[:id]
    @causes= @issue.causes.paginate(page: params[:page],  per_page: 5)
    @action_plans = ActionPlan.where("issue_id = " + @issue.id.to_s).paginate(page: params[:page], per_page: 5)
    @cof = CloseoutForm.find_by_issue_id(@issue.id)
  end

  private

  def auditor_user
      redirect_to(root_path) unless current_user.type_id==5
  end
  # Check for uniqueness later of Dept_id inside one COF before generating
end

app/controllers/dept/action_plan_comments_controller.rb
class Dept::ActionPlanCommentsController < ApplicationController
	before_filter :signed_in_user
	before_filter :dept_user
	
  	def create
	  @action_plan=ActionPlan.find_by_id(params[:action_plan_comment][:action_plan_id])
	  @apcomment= @action_plan.action_plan_comments.build(params[:action_plan_comment])
	  if @apcomment.save
	  	flash[:success] = "Comment added!"
	  	redirect_to [:dept, @action_plan]
	  else
	  	flash[:error] = "You cannot submit a blank comment!"
	  	redirect_to [:dept, @action_plan]
	  end
	end

	private
	def dept_user
      redirect_to(root_path) unless current_user.type_id==2
  end
end

app/controllers/dept/action_plans_controller.rb
class Dept::ActionPlansController < ApplicationController
  before_filter :signed_in_user
  before_filter :dept_user

  def new
  	@action_plan = ActionPlan.new
  end

  def create
  	@action_plan = ActionPlan.new(params[:action_plan])
    @action_plan.responsible_officer_id = current_user.id
    #since those who make action plans are responsible officers
    @issue = Issue.find(params[:action_plan][:issue_id])
  	if @action_plan.save
      @ic= @issue.issue_comments.build({content: "Officer added an Action Plan to Issue.",
            user_id: current_user.id, issue_id: @issue.id })
      @ic.toggle!(:log_comment)
      @ic.save
      @ac= @action_plan.action_plan_comments.build({content: "Officer submitted Action Plan.",
            user_id: current_user.id, action_plan_id: @action_plan.id })
      @ac.toggle!(:log_comment)
      @ac.save
  	  flash[:success] = "Successfully added Action Plan! Next, add an Activity for this Action Plan." 
  	  redirect_to new_dept_action_plan_activity_path(@action_plan)
  	else
  		flash.now[:error] = "Please fill in the fields properly." 
  		render 'new'
  	end
  end

  def edit
  	@action_plan = ActionPlan.find params[:id]
  end

  def update
  	@action_plan = ActionPlan.find params[:id]
    if @action_plan.update_attributes(params[:action_plan])
      @ac= @action_plan.action_plan_comments.build({content: "Officer updated Action Plan details.",
            user_id: current_user.id, action_plan_id: @action_plan.id })
      @ac.toggle!(:log_comment)
      @ac.save
      flash[:success] = "Action Plan updated."
      redirect_to dept_action_plan_path
    else
      flash.now[:error] = "Please don't leave the fields blank."
      render 'edit'
    end
  end

  def show
  	@action_plan = ActionPlan.find params[:id]
    @activities = @action_plan.activities.paginate(page: params[:page],  per_page: 5)
    @actionplan_comment = ActionPlanComment.new
    @ap_comments = @action_plan.action_plan_comments.where(log_comment: 'f').paginate(page: params[:page],  per_page: 3)
    @ap_updates = @action_plan.action_plan_comments.where(log_comment: 't').paginate(page: params[:page],  per_page: 5)
  end

  def index
  	@action_plans = ActionPlan.paginate(page: params[:page],  per_page: 10)
    @action_plans_yours = ActionPlan.where("responsible_officer_id = " + current_user.id.to_s).paginate(page: params[:page],  per_page: 5)
  end

  private

  def dept_user
      redirect_to(root_path) unless current_user.type_id==2
  end
end

app/controllers/dept/activities_controller.rb
class Dept::ActivitiesController < ApplicationController
  before_filter :signed_in_user
  before_filter :dept_user
  before_filter :actionplan_notnil
  before_filter :set_user

  def new
    @activity = Activity.new(params[:activity])
  end

  def create
    @activity = @action_plan.activities.build(params[:activity])
    @activity.user_id = @user.id 
    if @activity.save
      @ac= @action_plan.action_plan_comments.build({content: "Officer added an Activity to Action Plan.",
            user_id: current_user.id, action_plan_id: @action_plan.id })
      @ac.toggle!(:log_comment)
      @ac.save
      flash[:success] = "Successfully added Activity!" 
      redirect_to [:dept, @action_plan]
    else
      flash.now[:error] = "Please fill in the fields properly." 
      render 'new'
    end
  end

  def mark_done
    #@action_plan=ActionPlan.find(params[:action_plan_id])
    @activity = Activity.find(params[:id])
    #@activity.actual_date = Date.today
    @activity.status_id = 3
    if @activity.save
      #flash[:success] = "Activity marked as Implemented!"
      if @action_plan.ap_status_id < 3
        all_activities_implemented(@action_plan)
      else
        flash[:success] = "Activity marked as Implemented!"
        redirect_to [:dept, @action_plan]
      end
    end
  end

  def show
    @activity=Activity.find(params[:id])
  end

  def edit
    #@activity = Activity.find(params[:id])
    @activity = @action_plan.activities.find(params[:id])
  end

  def update
    #@activity = Activity.find(params[:id])
    @activity = @action_plan.activities.find(params[:id])
    if @activity.update_attributes(params[:activity])
      @ac= @action_plan.action_plan_comments.build({content: "Officer updated an Activity's details.",
            user_id: current_user.id, action_plan_id: @action_plan.id })
      @ac.toggle!(:log_comment)
      @ac.save
      flash[:success] = "Activity updated."
      redirect_to [:dept, @action_plan]
    else
      flash.now[:error] = "Please don't leave the fields blank."
      render 'edit'
    end
  end

  def destroy
    Activity.find(params[:id]).destroy
    @ac= @action_plan.action_plan_comments.build({content: "Officer deleted an Activity from Action Plan.",
            user_id: current_user.id, action_plan_id: @action_plan.id })
    @ac.toggle!(:log_comment)
    @ac.save
    flash[:success] = "Activity destroyed!"
    redirect_to [:dept, @action_plan]
  end

  private
    def actionplan_notnil
      @action_plan = ActionPlan.find(params[:action_plan_id])
      #redirect_to action_plans_path if @action_plan.nil?
    end

    def set_user
      @user = current_user
    end

    def dept_user
      redirect_to(root_path) unless current_user.type_id==2
    end

    def all_activities_implemented(action_plan)
      all_implemented = true
      if action_plan.activities != nil
        action_plan.activities.each do |act|
          if act.status_id != 3 && act.status_id != 6 
          # 2 is the status_id for Approved/Verified Activity, 6 for Rejected
          # Basically now ignores Rejected activities in checking if all Approved
            all_implemented = false
          # If there's a remaining Rejected Activity still undeleted, it won't register as all approved
          end
        end
      end
      if all_implemented
        action_plan.ap_status_id = 3
        if action_plan.save
          @ac= @action_plan.action_plan_comments.build({content: "Officer implemented all activities in Action Plan, Action Plan status updated.",
            user_id: current_user.id, action_plan_id: @action_plan.id })
          @ac.toggle!(:log_comment)
          @ac.save
          flash[:success] = "All Activities marked as Implemented, Action Plan status updated to Implemented. Activities now to be reviewed by Auditor."
          redirect_to dept_action_plan_path(action_plan)
        end
      else
        # Not all Implemented yet, normal redirect
        flash[:success] = "Activity marked as Implemented!"
        redirect_to [:dept, @action_plan]
      end
    end
end

app/controllers/dept/cause_attachments_controller.rb
class Dept::CauseAttachmentsController < ApplicationController
  before_filter :signed_in_user
  before_filter :dept_user
  before_filter :assigned_officer, only: :create

  def create
  	@cause = Cause.find_by_id(params[:cause_attachment][:cause_id])
    @cause_attachment = @cause.cause_attachments.build(params[:cause_attachment])
    @issue = Issue.find(@cause.issue_id)
    if @cause_attachment.save
      @cc= @cause.cause_comments.build({content: "User attached a file to Cause.",
            user_id: current_user.id, cause_id: @cause.id })
      @cc.toggle!(:log_comment)
      @cc.save
      flash[:success] = "File successfully Attached!"
      redirect_to [:dept, @issue, @cause]
    else
      flash[:error]  = "There was an error saving your file."
      redirect_to :back
    end
  end

  def destroy
  	@cause= Cause.find(params[:cause_id])
    @issue = Issue.find(@cause.issue_id)
    #redirect_to officer_issue_cause_path(@cause) if @cause.nil?
    @cause_attachment = @cause.cause_attachments.find_by_id(params[:id])
  	@cause_attachment.destroy
    @cc= @cause.cause_comments.build({content: "User deleted an attached file from Issue.",
            user_id: current_user.id, cause_id: @cause.id })
    @cc.toggle!(:log_comment)
    @cc.save
    flash[:success] = "File successfully removed from Cause!"
    redirect_to [:dept, @issue, @cause]
  end

  private
  	def dept_user
      redirect_to(root_path) unless current_user.type_id==2
  	end

  	def assigned_officer 
	    #@issue = Issue.find(params[:id])
	    @cause = Cause.find_by_id(params[:cause_attachment][:cause_id])
      @issue = Issue.find(@cause.issue_id)
	    @nrds = NextResponsibleDepartment.where("issue_id = ?", @issue.id)
	    found_nrds = false
	    @nrds.each do |n|
	      if n.responsible_officer_id == current_user.id
	        found_nrds = true
	      end
	    end
	    if found_nrds
	      flash[:success] = "Root Cause Adding/Editing by Secondary Officer" 
	    elsif @issue.responsible_officer_id != current_user.id
	      flash[:error] = "You're not allowed to Add or Edit Causes for Issues not assigned to you."
	      redirect_to [:dept, @issue, @cause]
	    end
  	end
end

app/controllers/dept/cause_comments_controller.rb
class Dept::CauseCommentsController < ApplicationController
	before_filter :signed_in_user
	before_filter :dept_user	

  	def create
	  @cause=Cause.find_by_id(params[:cause_comment][:cause_id])
	  @cause_comment= @cause.cause_comments.build(params[:cause_comment])
	  if @cause_comment.save
	  	flash[:success] = "Comment added!"
	  	redirect_to [:dept, Issue.find(@cause.issue_id), @cause]
	  else
	  	flash[:error] = "You cannot submit a blank comment!"
	  	redirect_to [:dept, Issue.find(@cause.issue_id), @cause]
	  end
	end

	private
	def dept_user
      redirect_to(root_path) unless current_user.type_id==2
  	end
end

app/controllers/dept/issue_comments_controller.rb
class Dept::IssueCommentsController < ApplicationController
	before_filter :signed_in_user
	before_filter :dept_user

  	def create
	  @issue=Issue.find_by_id(params[:issue_comment][:issue_id])
	  @issuecomment= @issue.issue_comments.build(params[:issue_comment])
	  if @issuecomment.save
	  	flash[:success] = "Comment added!"
	  	redirect_to [:dept, @issue]
	  else
	  	flash[:error] = "You cannot submit a blank comment!"
	  	redirect_to [:dept, @issue]
	  end
	end

	private
  	def dept_user
      redirect_to(root_path) unless current_user.type_id==2
  	end
end

app/controllers/dept/next_responsible_departments_controller.rb
class Dept::NextResponsibleDepartmentsController < ApplicationController
  before_filter :signed_in_user
  before_filter :dept_user

  def update
  	@issue = Issue.find_by_id(params[:next_responsible_department][:issue_id])
  	@nrd = NextResponsibleDepartment.find params[:id]
  	@nrd.dept_status_id = 3
  	if @nrd.update_attributes params[:next_responsible_department]
      flash[:success] = 'Successfully Assigned Officer to Issue. Issue is now Investigating Status (under Department).'
      redirect_to dept_issues_path
      title = "Assigned Officer to an Issue"
      content = "You have been assigned by your Department Head as a Responsible Officer for an Issue. Please check back into the site for the Issue details."
      @officer = User.find(params[:next_responsible_department][:responsible_officer_id])
      @officer.send_notification_email(title, content)
    else
      redirect_to :back, notice: 'There was an error in assigning.'
    end
  end

  private
  def dept_user
    redirect_to(root_path) unless current_user.type_id==2
  end

end

app/helpers/auditor/issues_helper.rb
module Auditor::IssuesHelper
end

app/helpers/dept/action_plans_helper.rb
module Dept::ActionPlansHelper
end

app/helpers/dept/activities_helper.rb
module Dept::ActivitiesHelper
end

app/views/dept/issues/_actionplans_show.html.erb
<!--Functions as Action Plan index show for Current Issue -->
<h3>Showing Action Plans</h3>
<p>Action Plans found for this Issue: <%= @action_plans.count %></p>

<table class="table table-striped table-bordered">
    <tr>
      <th>Description</th>
      <th>Submitted by</th>
      <th>Status</th>
      <th>Final Review Date</th>
      <th>Final Implementation Date</th>
      <th></th>

    </tr>

    <% @action_plans.each do |ap| %>
      <tr>
        <td><%= ap.description %></td>
        <td><% if ap.responsible_officer_id == nil %> 
              User Name
            <% else %>
              <%= User.find(ap.responsible_officer_id).name %>
            <% end %>
        </td>
        <td><%= ActionPlanStatus.find(ap.ap_status_id).name %></td>
        <td><%= ap.final_review_date %></td>
        <td><%= ap.final_implementation_review_date %></td>
        <td> 
          <%= link_to "View", [:dept, ap], class: "btn btn-primary" %>
        </td>
      </tr>
    <% end %>
</table>
<%= will_paginate @action_plans %>

app/views/dept/issues/_attachedfiles_show.html.erb
  <div class="span5">
    <h4>Files</h4>
    <hr>
    <% if @issue.issue_attachments.any? %>
      <%= @issue.issue_attachments.count %> files attached to this Issue:
      <% @issue.issue_attachments.each do |issue_attachment| %>
        <p>
          <!--<% if issue_attachment.myfile.file.extension == 'pdf' || issue_attachment.myfile.file.extension == 'doc' || issue_attachment.myfile.file.extension == 'docx'%>
            <%= image_tag preview_or_default_image(issue_attachment) if issue_attachment.myfile? %>
            <iframe src=<%= ["http://docs.google.com/gview?url=", Rails.root.join(issue_attachment.myfile_url), "&embedded=true"].join %> style="width:600px; height:500px;" frameborder="0"></iframe>
          <% else %>
            <%= image_tag preview_or_default_image(issue_attachment) if issue_attachment.myfile? %>
          <% end %>-->
          <% if issue_attachment.myfile.file.extension == 'pdf' || issue_attachment.myfile.file.extension == 'doc' || issue_attachment.myfile.file.extension == 'docx' %>
            <i class="icon-file"></i>
          <% elsif issue_attachment.myfile.file.extension == 'jpg' || issue_attachment.myfile.file.extension == 'jpeg' || issue_attachment.myfile.file.extension == 'png' || issue_attachment.myfile.file.extension == 'bmp'|| issue_attachment.myfile.file.extension == 'gif' %>
            <i class="icon-picture"></i>
          <% else %>
            <i class="icon-search"></i>
          <% end %>
          <b><i><%= link_to File.basename(issue_attachment.myfile.url), issue_attachment.myfile.url %></i></b> | 
          <%= issue_attachment.description %> |
          <%= link_to "View file", issue_attachment.myfile.url, target: '_blank' %>
          <% if current_user.id == issue_attachment.user_id %>
            | <%= link_to "delete", issue_attachment_path(issue_attachment, issue_id: @issue.id), confirm: "Are you sure you want to delete this File?", method: :delete  %>
          <% end %>
        </p>
        <br>
      <% end %>
    <% end %>
  </div>

app/views/dept/issues/index.html.erb
<% provide(:title, 'Department: Issues Index') %>
<h1><%= "Department Head: #{current_user.name}" %></h1>
<h2><%= "Department: #{Department.where(id: current_user.department_id).first.name}" %></h2>

<ul class="nav nav-pills">
  <li class="<%= 'active' if params[:sort] == nil %>"><%= link_to "All Issues",dept_issues_path %></li>
  <li class="<%= 'active' if params[:sort] == '1' %>"><%= link_to "New Issues", dept_issues_path(sort: '1') %></li>
  <li class="<%= 'active' if params[:sort] == '2' %>"><%= link_to "Verified Issues", dept_issues_path(sort: '2') %></li>
  <li class="<%= 'active' if params[:sort] == '3' %>"><%= link_to "Investigating Issues", dept_issues_path(sort: '3') %></li>
  <li class="<%= 'active' if params[:sort] == '4' %>"><%= link_to "Correcting Issues", dept_issues_path(sort: '4') %></li>
  <li class="<%= 'active' if params[:sort] == '5' %>"><%= link_to "Issues for Closeout", dept_issues_path(sort: '5') %></li>
  <li class="<%= 'active' if params[:sort] == '6' %>"><%= link_to "Closed Issues", dept_issues_path(sort: '6') %></li>
  <li class="<%= 'active' if params[:sort] == '7' %>"><%= link_to "Rejected Issues", dept_issues_path(sort: '7') %></li>
</ul>

<% case params[:sort] %>
<% when '1' %>
  <h2>New Issues for Approval</h2>
<% when '2' %>
  <h2>Verified Issues for Officer Assignment</h2>
<% when '3' %>
  <h2>Investigating Issues</h2>
<% when '4' %>
  <h2>Correcting Issues</h2>
<% when '5' %>
  <h2>Issues for Closeout</h2>
<% when '6' %>
  <h2>Closed Issues</h2>
<% when '7' %>
  <h2>Rejected Issues</h2>  
<% else %>
  <h2>Department: Showing All Issues</h2>
<% end %>

<table class="table table-striped table-bordered">
    <tr>
      <th>Title</th>
      <th>Originator</th>
      <th>Impact</th>
      <th>Status</th> <!--replaced Department in favor of Status-->
      <th>Type</th>
      <th>ISO Id</th>
      <th>Assigned To</th>
      <th></th>
    </tr>

    <% @issues.each do |issue| %>
      <tr>
        <td> <%= link_to issue.title, dept_issue_path(issue) %> </td>
        <td> <%= issue.user.name %> </td>
        <td> <% if issue.impact_id == 1 %>
              <span class="label label-important"><%= issue.issue_impact.name %></spn>
              <% elsif issue.impact_id == 2 %>
                <span class="label label-warning"><%= issue.issue_impact.name %></spn>
              <% else %>
                <span class="label label-info"><%= issue.issue_impact.name %></spn>
            <% end %>
        </td>
        <td> <%= issue.issue_status.name %> </td>
        <td> <%= issue.issue_type.name %></td>
        <td> <%= issue.iso_nc.title %></td>
        <td> <% if issue.responsible_officer_id == nil %>
                None
             <% else %>
                <%= User.find(issue.responsible_officer_id).name %>
             <% end %>
        </td>
        <td><%= link_to 'Details', details_dept_issue_path(issue), class: "btn btn-primary" %></td>
      </tr>
    <% end %>

  </table>
  <%= will_paginate @issues %>

app/views/dept/issues/show.html.erb
<% provide(:title, 'Show Issue') %>
<div class="row">
  <div class="span6">
    <p id="notice"> <%= notice %> </p>
 
    <h3>
      <!--<b>Title:</b> Use this instead for header-->
      <%= @issue.title %>
    </h3>

    <p>
      <b>Status:</b>
      <%= @issue.issue_status.name %>
    </p>

    <p>
      <b>Estimated Closeout Date:</b>
      <%= @issue.estimated_closeout_date %>
    </p>

    <% if @issue.status_id > 1 && @issue.status_id < 5 && found_dept(@issue) %>
      <%= form_for [:dept, @issue], url: {action: "update_date", method: "put"} do |f| %>
        <%= f.date_field :estimated_closeout_date, start_year: 2013 %>
        <small>(click on rightmost arrow for calendar selector)</small>
        <%= f.submit "Update Closeout Date", class: "btn btn-primary" %>
      <% end %>
    <% end %>

    <% if @issue.closeout_forms.count == 1 && @issue.status_id == 5 %>
      <p>Closeout form started, View it in details. </p>
    <% end %>

    <hr>

    <h4>Issue Details</h4>

    <p>
      <b>Description:</b>
      <%= @issue.description %>
    </p>
 
    <p>
      <b>Originator:</b>
      <%= @issue.user.name %>
    </p>

    <p>
      <b>Originator Email:</b>
      <%= @issue.user.email %>
    </p>

    <p>
      <b>Departments:</b>
      <%= @issue.department.name %>
      <% if @issue.next_responsible_departments.any? %>
        <% @issue.next_responsible_departments.each do |nrd| %>
          <%= ", "+ Department.where(id: nrd.department_id).first.name %>
          <!--+ " (" + nrd.responsibility_level.to_s + ")"-->
        <% end %>
      <% end %>
    </p>

    <p>
      <b>Type:</b>
      <%= @issue.issue_type.name %>
    </p>
 
    <p>
      <b>Impact:</b>
      <% if @issue.impact_id == 1 %>
        <span class="label label-important"><%= @issue.issue_impact.name %></spn>
      <% elsif @issue.impact_id == 2 %>
        <span class="label label-warning"><%= @issue.issue_impact.name %></spn>
      <% else %>
        <span class="label label-info"><%= @issue.issue_impact.name %></spn>
      <% end %>
    </p>

    <p>
      <b>ISO Reference ID:</b>
      <%= @issue.iso_nc.title %>
    </p>

    <p>
      <b>Assigned Officer: </b> 
        <% if @issue.responsible_officer_id != nil %>
          <%= User.find(@issue.responsible_officer_id).name %>
        <% else %>
          None
        <% end %>
    </p>

    <% if @issue.status_id == 2 && @issue.responsible_officer_id == nil && @issue.department_id == current_user.department_id %>
      <%= render 'assign' %>
    <% end %>
    <% if @nrd!= nil && @nrd.responsible_officer_id == nil && @nrd.department_id == current_user.department_id %>
      <%= render 'assign_secondary' %>
    <% end %>
    <%= link_to 'Show Details', details_dept_issue_path, class: "btn btn-primary" %>
    <%= link_to 'Back', dept_issues_path, class: "btn btn-primary" %>
    <hr>
    <%= render 'attachedfiles_show' %>
  </div>
  <%= render 'comments_show' %>
  
  <% if @issue.found_officer(current_user.id) %>
  <div class="span9">
    <hr>
    <%= render 'causes_show' %>
    <% if @issue.found_officer(current_user.id) %>
      <%= link_to 'Add Cause', new_dept_issue_cause_path(@issue) , class: "btn btn-small btn-primary" %>
    <% end %>
    <%= render 'actionplans_show' %>
    <% if @issue.found_officer(current_user.id) %>
      <% if @issue.causes.where("user_id = ?", current_user.id).empty? %>
        Add a Cause above first before adding an Action Plan
      <% else %>
        <%= link_to 'Add New Action Plan', new_dept_action_plan_path(issue_id: @issue.id), class: "btn btn-small btn-primary" %>
      <% end %>
    <% end %>
  </div>
  <% end %>

</div>